// Generated by https://quicktype.io

import 'group.dart';
import 'msg_index.dart';

class Category {
  final int id;
  final List<Group> groups;
  final int localisedNameIndex;
  final String sourceName;

  Category({this.id, this.groups, this.localisedNameIndex, this.sourceName});

  factory Category.fromMap(
      {Map<String, dynamic> map, List<Group> groups = null}) {
    var localeDetails = MsgIndex.lookupLocalisation(map["zh_name"] ?? '0');
    var name = map["sourceName"] ?? localeDetails.sourceName;
    return Category(
      id: map["id"],
      localisedNameIndex:
          map["localisedNameIndex"] ?? localeDetails.localisationIndex,
      sourceName: name,
      groups: groups ?? [],
    );
  }

  Map<String, dynamic> toJson() => {
        "id": id,
        "groups": groups.map((e) => e.id).toList(),
        "localisedNameIndex": localisedNameIndex,
        "sourceName": sourceName,
      };
}
