// Generated by https://quicktype.io

import 'item.dart';
import 'msg_index.dart';

class Group {
  final int id;
  final bool anchorable;
  final bool anchored;
  final bool fittableNonSingleton;
  final String iconPath;
  final bool useBasePrice;
  final int localisedNameIndex;
  final String sourceName;
  final List<Item> items;

  Group(
      {this.id,
      this.anchorable,
      this.anchored,
      this.fittableNonSingleton,
      this.iconPath,
      this.useBasePrice,
      this.localisedNameIndex,
      this.sourceName,
      this.items});

  factory Group.fromMap({Map<String, dynamic> map, List<Item> items = null}) {
    var localeDetails = MsgIndex.lookupLocalisation(map["zh_name"] ?? '0');
    var name = map["sourceName"] ?? localeDetails.sourceName;
    return Group(
      id: map["id"],
      anchorable: map["anchorable"],
      anchored: map["anchored"],
      fittableNonSingleton: map["fittable_non_singleton"],
      iconPath: map["icon_path"],
      useBasePrice: map["use_base_price"],
      sourceName: name,
      localisedNameIndex:
          map["localisedNameIndex"] ?? localeDetails.localisationIndex,
      items: items ?? [],
    );
  }

  Map<String, dynamic> toJson() => {
        "id": id,
        "anchorable": anchorable,
        "anchored": anchored,
        "fittable_non_singleton": fittableNonSingleton,
        "icon_path": iconPath,
        "use_base_price": useBasePrice,
        "sourceName": sourceName,
        "localisedNameIndex": localisedNameIndex,
        "items": items.map((e) => e.id).toList(),
      };
}
